version: "3.8"

services:
  postgres:
    image: postgres:15
    env_file:
      - ./config/.env.backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: tokamaknetwork/trh-backend@sha256:6e7e1c418ba3e1206f6a3a29e43780b74ca3882492bd8be04472c69ed3b839d7
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env.backend
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - backend_storage:/app/storage

  ui:
    image: tokamaknetwork/trh-platform-ui@sha256:7540d7f4ae1fe4b6034956aa44dc9fd96d1fe7db7b8c97ef07d12a1cb769bd75
    ports:
      - "3000:3000"
    env_file:
      - ./config/.env.frontend
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  backend_storage:
